---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: media
  namespace: media
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: media
      containers:
        - name: server
          image: nginx:1.22.0-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: assets
