---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "media.fullname" . }}
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  storageClassName: local
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/media
    type: DirectoryOrCreate
