namespace: external-dns
resources:
  - resource/Namespace/external-dns.yaml
  - github.com/kubernetes-sigs/external-dns/kustomize?ref=bb2606c50d1f602895795e945891c29f5418dd22
  - resource/Secret/dns-provider-credentials.yaml
patches:
  - path: patch/Deployment/external-dns.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: external-dns
