---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: media
spec:
  storageClassName: local
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Mi
