resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.yaml
  # - resource/Secret/dns-provider-credentials.yaml
  # - resource/ClusterIssuer/letsencrypt-prod.yaml
